[tool.poetry]
name = "site"
version = "0.1.0"
description = "Personal site"
authors = ["Jack Bradley <jack92829@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
